### ISSUE TITLE
General question - compliments

### ISSUE THREAD

**Issue by ritchiemarkov** [OpenGIS/Map-First#1]
Wow!

As usually my sincere compliments, i have missed OpenGIS foundation.

Great stuff!

My is more general question about this particular theme, and hope youll find some time just to clarify me 2 things.

My case: tailwind / alpine based theme.

Im trying to make a post type, for map visualizzation instead of all theme based only on map.

So in my case One single map shortcode, no collections. But i really like how this sidebar and elevation looks like.

Can you suggest me which files have to be included in order to make a post type with this functions?

I dont know, but you may consider to make a post-type only, instead of theme, cause in this way working with Waymark and Post type is easier rather then a full theme.

Thank you as always Joe!

**Comment by ritchiemarkov** [comment]
Ok Joe. I find out.

I'm pretty dumb.🤦

After importing correctly functions and scripts it's shows correctly on a map preview url. 

So ok time to ditch bootstrap away and implement good scrolling Y-axis dropdown with alpine and tailwind. 

Great job.

**Comment by morehawes** [comment]
Hi Richard,

Thank you for your kind words and my apologies for not getting back to you sooner. I was planning on doing a (video) response and even set it up... but of course everything takes longer than you imagine and I have not had time to revisit :0)

Have you figured out what you are trying to achieve? Feel free to share URLs/code and I would be happy to take a look. I have some experience with Tailwind/Alpine.

Thanks again,

Joe

**Comment by ritchiemarkov** [comment]
Hello Joe, yes im pretty figured out. Now trying to style it to match my theme. 

Its pretty hard but not impossible, layout is pretty much done, im going to make a carousel with "places" instead of dropdown list, since its better on mobile. So also swiper is involved.  Kids wanna have tailwind styling :), since it's cool xD

With your example there is a pretty big room to customize. Awesome, awesome, awesome! 

As i said, i have tryed to make something like your plugin, but its a nightmare at one point to handle every state of every function.

**Comment by morehawes** [comment]
> With your example there is a pretty big room to customize. Awesome, awesome, awesome!

:) I hope to keep improving [Map First](https://github.com/OpenGIS/Map-First), suggestions welcome!
